# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

"""Shared bootstrap steps for flow configurations.

There is no flow base class: each flow class composes the free functions in
this module in its own `__init__`, in the order that suits it, and keeps its
config state however it likes (the dict-based flows merge the hjson data
into their instance `__dict__`; the sim flow keeps a validated pydantic
model). The functions operate on a duck-typed flow object — see
`dvsim.flow.group.Flow` for the informal contract.

The usual sequence is:

    init_flow_state(self, flow_cfg_file, args)
    <merge the hjson data into the flow's config state>
    self.is_primary_cfg = "use_cfgs" in hjson_data
    default_rel_path(self)
    <apply config overrides>
    expand_wildcards(self)
    finalize_flow_state(self)
"""

import sys
from argparse import Namespace
from collections.abc import Mapping
from pathlib import Path

from dvsim.flow.hjson import set_target_attribute
from dvsim.job.data import WorkspaceConfig
from dvsim.logging import log
from dvsim.utils import find_and_substitute_wildcards
from dvsim.utils.git import git_commit_hash

__all__ = (
    "default_rel_path",
    "expand_wildcards",
    "finalize_flow_state",
    "init_flow_state",
    "merge_hjson",
    "process_overrides",
)


def init_flow_state(flow, flow_cfg_file: str, args: Namespace) -> None:
    """Initialise the state common to all flows.

    Sets the command-line driven options and the placeholders for the config
    keys that every flow relies on. Must run before the hjson data is merged.
    """
    # Options set from command line
    # Uniquify input items, while preserving the order.
    flow.items = list(dict.fromkeys(args.items))
    flow.list_items = args.list
    flow.select_cfgs = args.select_cfgs
    flow.flow_cfg_file = flow_cfg_file
    flow.args = args
    flow.scratch_root = args.scratch_root
    flow.branch = args.branch
    flow.job_prefix = args.job_prefix
    flow.gui = args.gui
    flow.gui_debug = args.gui_debug
    if flow.gui_debug:
        flow.gui = 1

    flow.interactive = args.interactive

    # Options set from hjson cfg.
    flow.name = ""
    flow.project = ""
    flow.scratch_path = ""
    flow.scratch_base_path = ""
    flow.proj_root = ""

    # The command line might specify the tool (with --tool). If not, we
    # leave it as None (allowing an hjson file to populate it)
    flow.tool = args.tool

    # Add exports using 'exports' keyword - these are exported to the child
    # process' environment.
    flow.exports = []

    # Add overrides using the overrides keyword - existing attributes
    # are overridden with the override values.
    flow.overrides = []

    # Set by the flow's __init__ once the hjson data is available: indicates
    # a primary cfg, which only groups child cfgs (see dvsim.flow.group).
    flow.is_primary_cfg = False

    # The list of job specs slated for dispatch.
    flow.deploy = []

    # Timestamp
    flow.timestamp_long = args.timestamp_long
    flow.timestamp = args.timestamp

    # Results
    flow.errors_seen = False
    flow.rel_path = ""
    flow.results_title = ""
    flow.revision = ""
    flow.css_file = Path(__file__).resolve().parent / "style.css"
    # `flow.results_*` below will be updated after `flow.rel_path` and
    # `flow.scratch_base_root` variables are updated.
    flow.results_dir = ""
    flow.results_page = ""
    flow.results_html_name = ""

    # Full results in md text
    flow.results_md = ""
    # Selectively sanitized md results to be published
    flow.publish_results_md = ""
    flow.sanitize_publish_results = False
    # Summary results, generated by over-arching cfg
    flow.results_summary_md = ""


def merge_hjson(flow, hjson_data: Mapping) -> None:
    """Merge hjson data into the flow's instance `__dict__`.

    This is for the dict-based flows; flows that keep their config in a
    separate store (see `SimCfg`) route the hjson data there instead.
    """
    for key, value in hjson_data.items():
        set_target_attribute(flow.flow_cfg_file, flow.__dict__, key, value)


def default_rel_path(flow) -> None:
    """Default the results path (relative to `proj_root`) to the cfg's dir."""
    if flow.rel_path == "":
        flow.rel_path = str(
            Path(flow.flow_cfg_file).parent.relative_to(flow.proj_root),
        )


def process_overrides(flow) -> None:
    """Apply the `overrides` list to the flow's attributes.

    Looks through the flow and finds available overrides. If an override is
    available, checks that the type of the value for the existing and the
    overridden keys are the same.

    This is for the dict-based flows; flows that keep their config in a
    separate store (see `SimCfg`) implement their own override handling.
    """
    overrides_dict = {}
    if hasattr(flow, "overrides"):
        overrides = flow.overrides
        if type(overrides) is not list:
            log.error(
                'The type of key "overrides" is %s - it should be a list',
                type(overrides),
            )
            sys.exit(1)

        # Process override one by one
        for item in overrides:
            if type(item) is dict and set(item.keys()) == {"name", "value"}:
                ov_name = item["name"]
                ov_value = item["value"]
                if ov_name not in overrides_dict:
                    overrides_dict[ov_name] = ov_value
                    _do_override(flow, ov_name, ov_value)
                else:
                    log.error(
                        'Override for key "%s" already exists!\nOld: %s\nNew: %s',
                        ov_name,
                        overrides_dict[ov_name],
                        ov_value,
                    )
                    sys.exit(1)
            else:
                log.error(
                    '"overrides" is a list of dicts with '
                    '{"name": <name>, "value": <value>} pairs. '
                    "Found this instead:\n%s",
                    str(item),
                )
                sys.exit(1)


def _do_override(flow, ov_name: str, ov_value: object) -> None:
    """Replace a flow attribute with an override value of matching type."""
    if hasattr(flow, ov_name):
        orig_value = getattr(flow, ov_name)
        if isinstance(ov_value, type(orig_value)):
            log.debug('Overriding "%s" value "%s" with "%s"', ov_name, orig_value, ov_value)
            setattr(flow, ov_name, ov_value)
        else:
            log.error(
                'The type of override value "%s" for "%s" '
                'doesn\'t match the type of original value "%s"',
                ov_value,
                ov_name,
                orig_value,
            )
            sys.exit(1)
    else:
        log.error('Override key "%s" not found in the cfg!', ov_name)
        sys.exit(1)


def expand_wildcards(flow) -> None:
    """Expand wildcards in the flow's config state after merging hjson.

    The flow provides the namespace via `wildcard_namespace()` and routes
    the expanded values back via `apply_expansion()`.
    """
    # If this is a primary configuration, it doesn't matter if we don't
    # manage to expand everything.
    partial = flow.is_primary_cfg

    # If custom dump script is exist, replace with run_script attribute.
    if flow.args.dump_script is not None:
        flow.run_script = "{proj_root}/" + flow.args.dump_script

    namespace = flow.wildcard_namespace()
    flow.apply_expansion(
        find_and_substitute_wildcards(
            namespace,
            namespace,
            flow.ignored_wildcards,
            ignore_error=partial,
        ),
    )


def finalize_flow_state(flow) -> None:
    """Derive the flow state that depends on the expanded config.

    Checks `proj_root`, records revision metadata and constructs the results
    paths and the workspace config.
    """
    # Check that proj_root has indeed been defined in the hjson config file
    if not flow.proj_root:
        raise RuntimeError("Config file did not define proj_root.")

    # After initialisation & expansion, save some useful revision metadata
    proj_root = Path(flow.proj_root)
    flow.commit = git_commit_hash(path=proj_root, short=False)
    flow.commit_short = git_commit_hash(path=proj_root, short=True)

    # Construct the path variables after variable expansion.
    reports_dir = Path(flow.scratch_base_path) / "reports"
    flow.results_dir = reports_dir / flow.rel_path
    flow.results_page = flow.results_dir / flow.results_html_name

    # Construct the global workspace config
    flow.workspace_cfg = WorkspaceConfig(
        timestamp=flow.args.timestamp,
        project_root=proj_root,
        scratch_root=Path(flow.scratch_root),
        scratch_path=Path(flow.scratch_path),
    )
