# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

"""Shared bootstrap steps for flow configurations.

There is no flow base class: each flow class composes the free functions in
this module in its own `__init__`, in the order that suits it. The config
state lives in a validated pydantic model (see `dvsim.flow.config`) while
runtime state lives on the instance. The functions operate on a duck-typed
flow object — see `dvsim.flow.group.Flow` for the informal contract.

The usual sequence is:

    init_flow_state(self, flow_cfg_file, args)
    merge_flow_config(self, hjson_data, model_cls=...)
    self.is_primary_cfg = "use_cfgs" in hjson_data
    default_rel_path(self)
    process_config_overrides(self)
    expand_wildcards(self)
    finalize_flow_state(self)
"""

from argparse import Namespace
from pathlib import Path

from dvsim.job.data import WorkspaceConfig
from dvsim.utils import find_and_substitute_wildcards
from dvsim.utils.git import git_commit_hash

__all__ = (
    "default_rel_path",
    "expand_wildcards",
    "finalize_flow_state",
    "init_flow_state",
)


def init_flow_state(flow, flow_cfg_file: str, args: Namespace) -> None:
    """Initialise the state common to all flows.

    Sets the command-line driven options and the placeholders for the config
    keys that every flow relies on. Must run before the hjson data is merged.
    """
    # Options set from command line
    # Uniquify input items, while preserving the order.
    flow.items = list(dict.fromkeys(args.items))
    flow.list_items = args.list
    flow.select_cfgs = args.select_cfgs
    flow.flow_cfg_file = flow_cfg_file
    flow.args = args
    flow.scratch_root = args.scratch_root
    flow.branch = args.branch
    flow.job_prefix = args.job_prefix
    flow.gui = args.gui
    flow.gui_debug = args.gui_debug
    if flow.gui_debug:
        flow.gui = 1

    flow.interactive = args.interactive

    # Options set from hjson cfg.
    flow.name = ""
    flow.project = ""
    flow.scratch_path = ""
    flow.scratch_base_path = ""
    flow.proj_root = ""

    # The command line might specify the tool (with --tool). If not, we
    # leave it as None (allowing an hjson file to populate it)
    flow.tool = args.tool

    # Add exports using 'exports' keyword - these are exported to the child
    # process' environment.
    flow.exports = []

    # Add overrides using the overrides keyword - existing attributes
    # are overridden with the override values.
    flow.overrides = []

    # Set by the flow's __init__ once the hjson data is available: indicates
    # a primary cfg, which only groups child cfgs (see dvsim.flow.group).
    flow.is_primary_cfg = False

    # The list of job specs slated for dispatch.
    flow.deploy = []

    # Timestamp
    flow.timestamp_long = args.timestamp_long
    flow.timestamp = args.timestamp

    # Results
    flow.errors_seen = False
    flow.rel_path = ""
    flow.results_title = ""
    flow.revision = ""
    flow.css_file = Path(__file__).resolve().parent / "style.css"
    # `flow.results_*` below will be updated after `flow.rel_path` and
    # `flow.scratch_base_root` variables are updated.
    flow.results_dir = ""
    flow.results_page = ""
    flow.results_html_name = ""

    # Full results in md text
    flow.results_md = ""
    # Selectively sanitized md results to be published
    flow.publish_results_md = ""
    flow.sanitize_publish_results = False
    # Summary results, generated by over-arching cfg
    flow.results_summary_md = ""


def default_rel_path(flow) -> None:
    """Default the results path (relative to `proj_root`) to the cfg's dir."""
    if flow.rel_path == "":
        flow.rel_path = str(
            Path(flow.flow_cfg_file).parent.relative_to(flow.proj_root),
        )


def expand_wildcards(flow) -> None:
    """Expand wildcards in the flow's config state after merging hjson.

    The flow provides the namespace via `wildcard_namespace()` and routes
    the expanded values back via `apply_expansion()`.
    """
    # If this is a primary configuration, it doesn't matter if we don't
    # manage to expand everything.
    partial = flow.is_primary_cfg

    # If custom dump script is exist, replace with run_script attribute.
    if flow.args.dump_script is not None:
        flow.run_script = "{proj_root}/" + flow.args.dump_script

    namespace = flow.wildcard_namespace()
    flow.apply_expansion(
        find_and_substitute_wildcards(
            namespace,
            namespace,
            flow.ignored_wildcards,
            ignore_error=partial,
        ),
    )


def finalize_flow_state(flow) -> None:
    """Derive the flow state that depends on the expanded config.

    Checks `proj_root`, records revision metadata and constructs the results
    paths and the workspace config.
    """
    # Check that proj_root has indeed been defined in the hjson config file
    if not flow.proj_root:
        raise RuntimeError("Config file did not define proj_root.")

    # After initialisation & expansion, save some useful revision metadata
    proj_root = Path(flow.proj_root)
    flow.commit = git_commit_hash(path=proj_root, short=False)
    flow.commit_short = git_commit_hash(path=proj_root, short=True)

    # Construct the path variables after variable expansion.
    reports_dir = Path(flow.scratch_base_path) / "reports"
    flow.results_dir = reports_dir / flow.rel_path
    flow.results_page = flow.results_dir / flow.results_html_name

    # Construct the global workspace config
    flow.workspace_cfg = WorkspaceConfig(
        timestamp=flow.args.timestamp,
        project_root=proj_root,
        scratch_root=Path(flow.scratch_root),
        scratch_path=Path(flow.scratch_path),
    )
