# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSES for details.
# SPDX-License-Identifier: Apache-2.0

name: Python application

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v24

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - uses: actions/checkout@v4

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4

    - name: Nix Format Check
      run: nix fmt -- . --check


    - name: Set up Python
      run: uv python install 3.13

    - name: Install the project
      run: |
        uv sync --all-extras
        source .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV

    - name: Lint with Ruff
      run: |
        ruff format  --check

    - name: Check with Ruff (All rules)
      run: |
        ruff check --statistics
      continue-on-error: true

    - name: Check with Ruff
      run: |
        ruff check --config=ruff-ci.toml --output-format=github

    - name: Type check with pyright
      run: |
        pyright
      continue-on-error: true

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install the project
      run: |
        uv sync --all-extras
        source .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
        sudo apt install -y rclone

    - name: Test with pytest
      run: |
        pytest

